---
sudo: required
3
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y expect

language: node_js
node_js:
- "7"

notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - narendrasoni2@gmail.com

deploy:
  skip_cleanup: true
  provider: script
  script: expect ./scripts/expect.js
  on:
    branch: ["master"]